/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 06-sept.-2019 8:07:50 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

USE GapSeguros
GO

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Poliza_EstadoPoliza]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Poliza] DROP CONSTRAINT [FK_Poliza_EstadoPoliza]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Poliza_TipoCubrimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Poliza] DROP CONSTRAINT [FK_Poliza_TipoCubrimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Poliza_TipoRiesgo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Poliza] DROP CONSTRAINT [FK_Poliza_TipoRiesgo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Poliza_Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Poliza] DROP CONSTRAINT [FK_Poliza_Usuario]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[EstadoPoliza]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [EstadoPoliza]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Poliza]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Poliza]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TipoCubrimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TipoCubrimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TipoRiesgo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TipoRiesgo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Usuario]
GO

/* Create Tables */

CREATE TABLE [EstadoPoliza]
(
	[id] int NOT NULL,
	[nombre] nvarchar(50) NOT NULL,
	[descripcion] nvarchar(150) NULL
)
GO

CREATE TABLE [Poliza]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nombre] nvarchar(50) NULL,
	[descripcion] nvarchar(150) NULL,
	[tipoCubrimientoId] int NOT NULL,
	[cobertura] decimal(18,5) NULL,
	[tipoRiesgoId] int NOT NULL,
	[fechaInicioVigencia] datetime2(7) NULL,
	[duracionMesesCobertura] int NULL,
	[precio] decimal(30,5) NULL,
	[estadoPolizaId] int NOT NULL,
	[usuarioId] int NOT NULL
)
GO

CREATE TABLE [TipoCubrimiento]
(
	[id] int NOT NULL,
	[nombre] nvarchar(50) NOT NULL,
	[descripcion] nvarchar(150) NULL
)
GO

CREATE TABLE [TipoRiesgo]
(
	[id] int NOT NULL,
	[nombre] nvarchar(50) NOT NULL,
	[descripcion] nvarchar(150) NULL
)
GO

CREATE TABLE [Usuario]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nombre] nvarchar(150) NOT NULL,
	[cedula] nvarchar(50) NOT NULL,
	[nombreUsuario] nvarchar(50) NOT NULL,
	[contrasenia] nvarchar(50) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [EstadoPoliza] 
 ADD CONSTRAINT [PK_EstadoPoliza]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Poliza] 
 ADD CONSTRAINT [PK_Poliza]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Poliza_EstadoPoliza] 
 ON [Poliza] ([estadoPolizaId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Poliza_TipoCubrimiento] 
 ON [Poliza] ([tipoCubrimientoId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Poliza_TipoRiesgo] 
 ON [Poliza] ([tipoRiesgoId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Poliza_Usuario] 
 ON [Poliza] ([usuarioId] ASC)
GO

ALTER TABLE [TipoCubrimiento] 
 ADD CONSTRAINT [PK_TipoCubrimiento]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [TipoRiesgo] 
 ADD CONSTRAINT [PK_TipoRiesgo]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Usuario] 
 ADD CONSTRAINT [PK_Usuario]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Poliza] ADD CONSTRAINT [FK_Poliza_EstadoPoliza]
	FOREIGN KEY ([estadoPolizaId]) REFERENCES [EstadoPoliza] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Poliza] ADD CONSTRAINT [FK_Poliza_TipoCubrimiento]
	FOREIGN KEY ([tipoCubrimientoId]) REFERENCES [TipoCubrimiento] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Poliza] ADD CONSTRAINT [FK_Poliza_TipoRiesgo]
	FOREIGN KEY ([tipoRiesgoId]) REFERENCES [TipoRiesgo] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Poliza] ADD CONSTRAINT [FK_Poliza_Usuario]
	FOREIGN KEY ([usuarioId]) REFERENCES [Usuario] ([id]) ON DELETE No Action ON UPDATE No Action
GO
